language: python
python:
  - "3.8"

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - prod

env: DJANGO_SETTINGS_MODULE="job_search_platform.settings.travis"

services:
  - sqlite3

script:
  - job_search_platform/manage.py test
