# Generated by Django 2.2.4 on 2019-08-07 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_platform', '0002_auto_20190807_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('alternance', models.BooleanField()),
                ('city', models.CharField(max_length=50)),
                ('contact_mode', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('headcount_text', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('naf', models.CharField(max_length=20)),
                ('naf_text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('raison_sociale', models.CharField(max_length=100)),
                ('siret', models.CharField(max_length=14)),
                ('stars', models.IntegerField()),
                ('url', models.URLField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rome_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='trade_to_rome_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_platform.rome_code')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_experiences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_infos',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user_infos',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='user_infos',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='user_education',
        ),
        migrations.DeleteModel(
            name='user_experiences',
        ),
        migrations.DeleteModel(
            name='user_job',
        ),
    ]
