# Generated by Django 2.2.4 on 2019-08-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0003_auto_20190807_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rome_code',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
