# Generated by Django 2.2.4 on 2019-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0004_auto_20190807_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='rome_code',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='trade_to_rome_code',
            name='job_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
