# Generated by Django 2.2.4 on 2019-08-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0005_auto_20190808_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_infos',
            old_name='adress',
            new_name='address',
        ),
    ]
