# Generated by Django 3.1.3 on 2020-12-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0008_remove_company_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_infos',
            name='job_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_platform.rome_code'),
            preserve_default=False,
        ),
    ]
