# Generated by Django 3.1.3 on 2020-12-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0009_user_infos_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infos',
            name='job_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_platform.rome_code'),
        ),
    ]
