# Generated by Django 2.1.5 on 2020-12-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0010_auto_20201223_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='company',
            name='naf',
        ),
        migrations.RemoveField(
            model_name='company',
            name='naf_text',
        ),
        migrations.RemoveField(
            model_name='company',
            name='raison_sociale',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stars',
        ),
    ]
