# Generated by Django 3.1.3 on 2020-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0011_auto_20201224_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
