# Generated by Django 2.1.5 on 2021-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0012_auto_20201224_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infos',
            name='address',
        ),
        migrations.AddField(
            model_name='user_infos',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user_infos',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
    ]
