# Generated by Django 2.1.5 on 2021-06-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0014_auto_20210605_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infos',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user_infos',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
    ]
