# Generated by Django 2.1.5 on 2021-06-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0015_auto_20210605_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_infos',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
