# Generated by Django 2.1.5 on 2021-06-16 01:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_platform', '0017_auto_20210616_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RomeCode',
            new_name='rome_code',
        ),
        migrations.RenameModel(
            old_name='TradeToRomeCode',
            new_name='trade_to_rome_code',
        ),
        migrations.RenameModel(
            old_name='UserInfos',
            new_name='user_infos',
        ),
    ]
