# Generated by Django 2.1.5 on 2021-06-16 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_platform', '0018_auto_20210616_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rome_code',
            new_name='RomeCode',
        ),
        migrations.RenameModel(
            old_name='trade_to_rome_code',
            new_name='TradeToRomeCode',
        ),
        migrations.RenameModel(
            old_name='user_infos',
            new_name='UserInfos',
        ),
    ]
