# Generated by Django 2.1.5 on 2021-06-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0019_auto_20210616_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradetoromecode',
            old_name='job_code',
            new_name='jobCode',
        ),
        migrations.RenameField(
            model_name='tradetoromecode',
            old_name='job_name',
            new_name='jobName',
        ),
        migrations.RenameField(
            model_name='userinfos',
            old_name='job_code',
            new_name='jobCode',
        ),
    ]
