# Generated by Django 2.1.5 on 2021-06-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0020_auto_20210616_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradetoromecode',
            old_name='jobCode',
            new_name='job_code',
        ),
        migrations.RenameField(
            model_name='tradetoromecode',
            old_name='jobName',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='userinfos',
            old_name='jobCode',
            new_name='job_code',
        ),
    ]
