# Generated by Django 2.1.5 on 2021-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0021_auto_20210616_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alternance',
            field=models.BooleanField(null=True),
        ),
    ]
